import Head from "next/head";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Images from "../components/Images";
import RightNav from "../components/RightNav";

export default function Home() {
  return (
    <div>
      <Head>
        <title>YASAMAN NOZARI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="App">
        <div className="app">
          <Header />
          <Images />
          <div className="right-nav-app">
            <RightNav />
          </div>
        </div>
        <Footer />

        <style jsx>{`
          .app {
            display: flex;
            flex-direction: row;
            flex-wrap: nowrap;
            align-items: flex-start;
            justify-content: flex-start;
            max-width: 900px;
          }

          @media only screen and (max-width: 700px) {
            .app {
              flex-wrap: wrap;
            }

            .right-nav-app {
              display: none;
            }
          }
        `}</style>
      </div>
    </div>
  );
}
